# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 945b54c6e67249e1d4d866dd045d08329d98698c

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@webpublico.com.br
    password: ehSenha10Sim!
    protocol: smtp
    tls: true
    auth: true
    from: suporte@webpublico.com.br

authentication:
    oauth:
        clientid: nfseapp
        secret: mySecretOAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 1800

swagger:
    title: nfse API
    description: nfse applications and beyond!
    version: 0.0.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

webpublico:
    api-key: fcc5f16f-452b-478e-8803-6d3d33fc68bf
